string = [ "5", "6", "5", "6", "5", "6", "5", "6", "5", "6", "5", "6", "5", "6", "5", "6"]

[[apps]]
 position=0
 rule=0

[[apps]]
 position=0
 rule=2

[[apps]]
 position=0
 rule=3

[[apps]]
 position=1
 rule=4

[[apps]]
 position=2
 rule=1

[[apps]]
 position=2
 rule=2

[[apps]]
 position=2
 rule=3

[[apps]]
 position=3
 rule=4

[[apps]]
 position=4
 rule=1

[[apps]]
 position=4
 rule=2

[[apps]]
 position=4
 rule=3

[[apps]]
 position=5
 rule=4

[[apps]]
 position=6
 rule=1

[[apps]]
 position=6
 rule=2

[[apps]]
 position=6
 rule=3

[[apps]]
 position=7
 rule=4

[[apps]]
 position=8
 rule=1

[[apps]]
 position=8
 rule=2

[[apps]]
 position=8
 rule=3

[[apps]]
 position=9
 rule=4

[[apps]]
 position=10
 rule=1

[[apps]]
 position=10
 rule=2

[[apps]]
 position=10
 rule=3

[[apps]]
 position=11
 rule=4

[[apps]]
 position=12
 rule=1

[[apps]]
 position=12
 rule=2

[[apps]]
 position=12
 rule=3

[[apps]]
 position=13
 rule=4

[[apps]]
 position=14
 rule=2

[[apps]]
 position=14
 rule=3

[[apps]]
 position=15
 rule=4

